# spring.mvc.date-format=yyyy-MM-dd HH:mm:ss
spring:
  mvc:
    dataFormat: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false