my-propss: #自定义的属性和值
  simple-prop: simplePropValue
  array-props: 1,2,3,4,5
  list-prop1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  list-prop2:
    - config2Value1
    - config2Vavlue2
  map-props:
    key1: value1
    key2: value2
  # 如下，亦可定义map类型，[${name}]会被解析为map的key，且不需要加上双引号。
  orderType[1]: 10
  orderType[2]: 10
  orderType[3]: 10
  userType[name]: dfz
  userType[age]: 18
  userType[address]: hf

cust:
  name:
  - lhr1
  - lhr