spring:
  datasource:
    url: jdbc:mysql://172.16.128.32:3306/etrading?useAffectedRows=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: 7RFGgtm7Sw0=
    password: V2NdLTRSXCI=